// import type { Metadata } from "next";
// import { ClarityCity } from "@/utils/customFont";

// import { Header } from "@/components/Header";
// import { Footer } from "@/components/Footer";
// import { SessionProvider } from "next-auth/react";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }


// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   )
// }

// auth/layout.tsx
import "../../app/globals.css";
// import { Sidebar } from "./_components/Sidebar"; // Adjust path as needed
// import { ClarityCity } from "@/utils/customFont";

// export default function AuthLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <div className={`${ClarityCity.variable} flex min-h-screen bg-gray-50`}>
//       {/* Sidebar */}
//       <Sidebar />

//       {/* Main Content Area */}
//       <div className="flex-1 pl-96 p-6">{children}</div>
//     </div>
//   );
// }
import { Sidebar } from "./_components/Sidebar"; // Adjust path as needed
import { ClarityCity } from "@/utils/customFont";

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ClarityCity.variable} flex min-h-screen bg-gray-50`}>
        {/* Sidebar */}
        <Sidebar />

        {/* Main Content Area */}
        <div className="flex-1 md:pl-96 p-6 mt-10 md:mt-0">{children}</div>
      </body>
    </html>
  );
}
