// import type { Metadata } from "next";
// import { ClarityCity } from "@/utils/customFont";


// import {Sidebar} from "./_components/Sidebar"
// export const metadata: Metadata = {
//   title: "DreamLegal",
//   description: "Generated by DreamLegal",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ClarityCity.variable} `}>
//       <div className="flex min-h-screen bg-gray-50">
//       {/* Sidebar */}
//       <Sidebar/>
      
      
//       <div className="flex-1 pl-96 p-6">
       
//       </div>
//     </div>
//       </body>
//     </html>
//   );
// }

// no need of this page


import { redirect } from "next/navigation";

export default function UserPage() {
  redirect("/auth/user/login"); // Redirect to user login page
}
